export const COMPONENT_EXTENSION = Symbol("COMPONENT_EXTENSION");
export const COMPONENT_NAME = Symbol("COMPONENT_NAME");
export const COMPONENT_SCOPE = Symbol("COMPONENT_SCOPE");
export const COMPONENT_CONSTRUCTOR_DEPENDENCIES = Symbol("COMPONENT_CONSTRUCTOR_DEPENDENCIES");
